source/Cosmos.Build.MSBuild/BaseToolTask.cs, source/Cosmos.Build.MSBuild/IL2CPU.cs
IL2CPU task modified to keep current behaviour
Added diagnosting reporting of the command line executed. This command line is visible only if you run MSBuild with Diagnostic level of verbosity
Related to #50
=> Don't report output from NAsm as error in case of warnings

source/Cosmos.HAL/Cosmos.HAL.csproj, source/Cosmos.IL2CPU/ILOpCodes/OpType.cs, source/Cosmos.IL2CPU/ILScanner.cs
(In relation to issue #72)
These changes add stobj's stack push/pop info to OpType. It looks like stobj was implemented, this information was just missing.
I ran into some [extra issues](https://github.com/CosmosOS/Cosmos/issues/72#issuecomment-94332305) with the sample code that caused this problem after I made this change, so it isn't as tested as I'd like.
There are two other less noteworthy changes in these commits:
* Added PCSpeaker.cs to the Cosmos.HAL project (it was accidentally removed recently, it seems.)
* I hacked in a change to make the call traces in IL2CPU's output slightly more useful when a plug is missing.
For the latter, it is a bit of a hack - so I understand if you don't want to merge it.
I just wasn't satisfied with MethodBase.ToString's output. It makes the output …
=> Added stobj stack push/pop information to OpType and some other smaller changes.

source/Cosmos.IL2CPU/CompilerEngine.cs, source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
String switch on Roslyn used operation Xor(UINT32, Char) which was currently not supported on IL2CPU.
By the way I fix dynamic assembly discovery which now shouldn't need try/catch so it don't mess up with debugging session when NotSupportetException is captured by debugger
=> Fix String switch on Roslyn

Tests/Cosmos.Compiler.Tests.Interfaces/Cosmos.Compiler.Tests.Interfaces.KernelBoot.Cosmos, Tests/Cosmos.Compiler.Tests.SimpleWriteLine.Kernel/Cosmos.Compiler.Tests.SimpleWriteLine.KernelBoot.Cosmos, Users/Emile/TestBed/TestBed/TestBedBoot.Cosmos, Users/Sentinel/SentinelKernel/SentinelKernelBoot.Cosmos
This allows to load projects using MSBuild when VS 2012 is not installed.
Since we don't support VS 2012, there no reason to have these files be in the old format.
These kernels lately would be used for unit testing, without that change this would not work.
=> Update the ToolsVersion value in the project files

source/Cosmos.HAL/TextScreen.cs, source/Cosmos.System.Plugs/System/ConsoleImpl.cs
(The methods that the screenshot shows as not implemented are implemented in this PR, but the bug is too, so I had to use Cosmos version from latest master to show the bug)
=> Implemented some console methods and fixed a bug in the console, copying the behaviour of background color in windows console applications.

source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
Fixed short|short bug. Causing errors during compilation.
`1> Error: Exception: System.Exception: Error compiling method 'SystemVoidLiquiDOSHALACPIShutdown': System.Exception: Error interpreting stacktypes for IL_0036: Or ---> System.NotImplementedException: Or on types 'System.Int16' and 'System.Int16' not yet implemented!`
=> Fixed (short-short) op bug

source/Cosmos.Assembler/Cosmos.Assembler.csproj, source/Cosmos.Assembler/x86/Lea.cs, source/Cosmos.Assembler/x86/Rdmsr.cs, source/Cosmos.Assembler/x86/Rdtsc.cs, source/Cosmos.Core.Plugs/Cosmos.Core.Plugs.csproj, source/Cosmos.Core.Plugs/System/DateTimeImpl.cs
Added the x86-instructions 'LEA', 'RDTSC' and 'RDMSR'.
Added a simplistic plug for 'system::datetime', which now contains the
method for fetching the current date/time
=> Added ASM instructions and basic DateTime-implementation

source/Cosmos.VS.Package/Templates/Projects/CosmosKernel (VB)/Kernel.vb, source/Cosmos.VS.Package/Templates/Projects/CosmosKernel (VB)/VBProjKernel.vbproj, source/Cosmos.VS.Package/Templates/Projects/CosmosProject (VB)/Kernel.vb, source/Cosmos.VS.Package/Templates/Projects/CosmosProject (VB)/VBProjKernel.vbproj
- Visual Basict projects do not accept ';' as separator between the constant definitions they accept instead ','
- The example kernel was wrong as nothing was really echoed back!
=> Fixed Template for Visual Basic kernel

Tests/Cosmos.Compiler.Tests.Bcl/Kernel.cs, Tests/Cosmos.TestRunner.Core/Engine.Running.cs, Tests/Cosmos.TestRunner.Core/TestKernelSets.cs
- Fixed the problem of every kernel counting as 2 kernels, and one of them was considered always successful.
- Commented FAT test
- Uncommented many BCL tests, as they were working fine, and 2 were left commented, as they were not working, with their problems commented to help solving the bugs
=> Tests fixes and minor changes

source/Cosmos.Build.Builder/CosmosTask.cs
The specified key doesn't always seem to exist in the builder, however there are keys that are always there (placed by VMware that are required to work) so check for those as a fallback.
=> Builder changes - better detection for VMware Player

source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
OS says Math.Round() is not implemented without the changes. It should work now!
=> Update OpNone.cs for Math.Round()

source/Cosmos.Core/ACPI.cs, source/Cosmos.HAL/Global.cs, source/Cosmos.HAL/Power.cs, source/Cosmos.System/Power.cs
- ACPI Enable and Disable removed from System and HAL
- ACPI Reboot deleted (because it is not a ACPI Reset...)
Now the user has two choice : Sys.Power.Shutdown (that uses ACPI) and Sys.Power.Reboot (that uses CPU).
=> ACPI Improvements.

source/Cosmos.VS.ProjectSystem/ProjectTemplates/CosmosKernel (VB)/VBProjKernel.vbproj, source/Cosmos.VS.ProjectSystem/ProjectTemplates/CosmosProject (CSharp)/CSharpProject.csproj, source/Cosmos.VS.ProjectSystem/ProjectTemplates/CosmosProject (FSharp)/FSharpProject.fsproj
I've fixed the references for the project templates, the CSharp project template is verified working, not too sure if the Visual Basic project template had other issues but the F Sharp project may have other issues too like beforehand. At least the C# project template is fixed now :)
=> Fixed the project templates for csproj, vbproj, and fsproj

Tests/Cosmos.Kernel.Tests.Fat/Kernel.cs, source/Cosmos.System2_Plugs/System/IO/FileImpl.cs
Since IL2CPU doesn't support arrays as `IEnumerable<T>`
I changed WriteAllLines code
and convert string[] into a string ends with '\r\n' based on windows for creating New Line
=> Fixing WriteAllLines issue

install-VS2017.bat
When someone new press the install.bat the builder runs but with error. It is needed to install explicit the new .net Framework.
This Version number to check is from Windows 10 creators, but on MSDN is written that the verison on older Version is different. please check that. reference: https://docs.microsoft.com/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#net_b
Furthermore it would be good to check if IL2CPU and Xsharp Projects also exists.
=> check in batch before build for.net framework 4.7.1

Setup/Cosmos.iss, source/Cosmos.Build.Builder/CosmosTask.cs, source/Cosmos.Build.Installer/Paths.cs
The builder should not wait until VS is closed, this is work of the Setup itself. Furthermore we check now for Addition applications which are checked by VSIXInstaller.exe before Installation.
=> move wait for VS into inno setup

source/Cosmos.HAL2/TextScreen.cs
- Fixes #559
- Clear the **seventh bit**(0) in `TextScreen.cs` at method `SetColors(ConsoleColor, ConsoleColor)`.
**No**, the real fix is to switch to real mode and clear in Mode Control Register (Index 10) the third bit to disable blinking and enable the background bright bit for dark gray and other brighten colors.
---
(0) = "Seventh bit is defaultly the blinking bit by the bios, if set to 1: the written text after the `SetColors` method will blink forever, if set to 0: none of the above will happen.
=> Fix Blinking Text on (VGA that can blink)

source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs, source/Cosmos.HAL2/PCI.cs
AMD Vendor ID is 0x1022 not 0x0438.
=> Little fix on PCI VendorID.

source/Cosmos.Build.Builder/CosmosTask.cs
As to why GitHub can't display the changes in a simple way, I don't know but I'll explain em anyway
```
private string mIL2CPUPath;
private string mXSPath;
```
IL2CPU and XSharp paths were added to CosmosTask class, and 
```
mXSPath = Path.GetFullPath(Path.Combine(mCosmosPath, @"..\XSharp"));
mIL2CPUPath = Path.GetFullPath(Path.Combine(mCosmosPath, @"..\IL2CPU"));
```
were added to the CosmosTask constructor, with a new method that does the following:
```
private void CheckForRepos()
{
Log.WriteLine("Checking for existing IL2CPU and XSharp repositories...");
if (!Directory.Exists(mIL2CPUPath))
{
if (!File.Exists(Path.Combine(mIL2CPUPath, @"IL2CPU.sln")))
{
mExceptionList.Add("Missing IL2CPU Repository! Make sure to clone IL2CPU in the parent directory of Cosmos! Download IL2CPU and …
```
=> Add checks for IL2CPU and XSharp repositories and solution files

source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs
(previously limited to 255 bytes)
=> [PCNETII] Little fix on packet size

source/Cosmos.HAL2/BlockDevice/AtaPio.cs
Fixes #1056: Does not boot if there is no IDE Secondary Master
(VirtualBox)
See https://wiki.osdev.org/ATA_PIO_Mode#Floating_Bus
=> Check for floating bus

source/Cosmos.Common/ByteToString.cs, source/Cosmos.Common/StringHelper.cs
Added new condition check on the str that passed to the StrToByteArray function.
This condition check if the passed string is in a numeric format.
Currently there is no check for this, and as byte.Parse is called on the non-numeric string it throws System.FormatException, which is currently seems to be unhandled, causing CPU exception.
This condition should prevent this behaviour.
This problem discussed on #1333 issue.
=> Added condition on StrToByteArray in order to prevent CPU exception

source/Cosmos.Core/Cosmos.Core.csproj, source/Cosmos.Core_Asm/Cosmos.Core_Asm.csproj, source/Cosmos.Core_Plugs/Cosmos.Core_Plugs.csproj, source/Cosmos.Debug.Kernel.Plugs.Asm/Cosmos.Debug.Kernel.Plugs.Asm.csproj, source/Cosmos.Debug.Kernel/Cosmos.Debug.Kernel.csproj, source/Cosmos.HAL2/Cosmos.HAL2.csproj, source/Cosmos.System2/Cosmos.System2.csproj, source/Cosmos.System2_Plugs/Cosmos.System2_Plugs.csproj, source/Kernel-TapRoot/Demo/TRKernel.csproj, source/Kernel-X86/10-CPU/Cosmos.CPU.x86/Cosmos.CPU.x86.csproj, source/Kernel-X86/10-CPU/Cosmos.CPU_Asm/Cosmos.CPU_Asm.csproj, source/Kernel-X86/10-CPU/Cosmos.CPU_Plugs/Cosmos.CPU_Plugs.csproj, source/Kernel-X86/20-Platform/Cosmos.Platform.PC/Cosmos.Platform.PC.csproj, source/Kernel-X86/30-HAL/Cosmos.HAL/Cosmos.HAL.csproj, source/Kernel-X86/40-System/Cosmos.System/Cosmos.System.csproj, source/Kernel-X86/50-Application/GuessKernelGen3.csproj, source/Kernel-X86/91-Plugs/Cosmos.Plugs.TapRoot/Cosmos.Plugs.TapRoot.csproj
Currently any API documentation of any cosmos lib is unavailable for the user.
When using the userkit, you can not see any reference of any method of cosmos.
Added GenerateDocumentationFile property in all the libs, so xml documentation would be generated with the NuGet package.
There is a lot of benefits in letting the users to see it.
Notice: This might slow down the IDE for some low-end PCs
=> Made API documentation visable while using the userkit

source/Cosmos.System2/Graphics/Bitmap.cs
Adobe Photoshop uses a not well documented header format `BITMAPV3INFOHEADER`, see https://web.archive.org/web/20150127132443/https://forums.adobe.com/message/3272950. 
Closes https://github.com/CosmosOS/Cosmos/issues/1391
=> Add support for BITMAPV3INFOHEADER

source/Cosmos.System2/Graphics/VBECanvas.cs
Alpha rendering in 32bpp mode
fix https://github.com/CosmosOS/Cosmos/issues/1398
=> CGS Alpha Rendering

Tests/Kernels/GraphicTest/Kernel.cs, source/Cosmos.System2/Graphics/Canvas.cs
Implement Bitmap Scaling by Desired Height and Width
Should close #1518
=> Implement Bitmap Scaling

source/Cosmos.HAL2/BlockDevice/IDE.cs
Enabling Slaves on the IDE causes no Issues it rather enables HDD detection on Computers that did not detect the hdd beforehand, ie. Laptops that assing the Optical Drive as Master and the HDD as Slave.
=> Enable Slaves on IDE

source/Cosmos.HAL2/PCI.cs
Useful to be able to get multiples PCI devices with the same Vendor ID & Device ID.
=> Add GetDevice function with bus, slot, function informations

source/Cosmos.HAL2/Drivers/Video/VBEDriver.cs
Real hardware doesn't often use a linear framebuffer. It can causes graphics issues.
=> Implement non linear framebuffer detection for VBE multiboot

Docs/articles/Kernel/Network.md
Because we're already utilizing `using` statements, Close() calls aren't necessary since the statement will automatically close and dispose the object.
=> [Documentation] Remove useless Close() calls

appveyor.yml
Fixes #1820, excludes the Docs/ folder in commits to save AppVeyor rebuilding if just the docs change.
If there are changes in a commit including source code as well, it will build that commit as there is no rule matching - source/
=> Fixes #1820

source/Cosmos.System2/FileSystem/CosmosVFS.cs, source/Cosmos.System2/FileSystem/VFS/VFSBase.cs, source/Cosmos.System2/FileSystem/VFS/VFSManager.cs, source/Cosmos.System2/Graphics/SVGAIICanvas.cs
This boolean, if true, will print info about the drive's partitions and other stuff. It was true by default and there was no option to disable it before, and we don't always need to have the info printed.
Also, don't worry about the 2 commits before, it was just me commiting to the wrong branch :v
=> Add VFSManager.Initialize(bool aShowInfo)

appveyor.yml
GitHub doesn't have a 'skipped' build status for CI providers, and only has failure or success statuses (boolean?).  AppVeyor would either need to send a succeed status to the GitHub PR in order for merging to be available, or GitHub need to add a new skipped status in its API. A webhook can be setup using a Personal Access Token to manually set the build status to 'succeeded'/'fail'
=> Revert Appveyor.yml changes due to API issues

install-VS2019.bat
Source : https://github.com/NuGet/NuGetGallery/issues/8176#issuecomment-683923724
This enables TLS 1.2 in the registry if a certain update is installed.
=> Fix building on Windows 7

source/Cosmos.System2_Plugs/System/ConsoleImpl.cs
Added checks for x & y to be at least 0. Also updated error messages to use exceptions.
=> Update ConsoleImpl.cs to use exceptions

source/Cosmos.System2/Kernel.cs
Several users found them annoying. They can be easily added manually by whoever wants them.
=> Remove before-after Run() debug lines

source/Cosmos.HAL2/PCSpeaker.cs
=> Make PCSpeaker use Hal.Global pit instance

source/Cosmos.System2/Graphics/VBECanvas.cs
The previous function would draw each line without trimming it to fit the canvas width, therefore creating some weird visual bugs - the rectangle would be drawn from the left side of the screen, even though it would have gone far beyond the video mode's width.
An example of the old bug, that's now fixed: https://discord.com/channels/833970409337913344/833979135466405899/912805747597926421
=> Fix VBECanvas#DrawFilledRectangle

Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/System/ByteTest.cs, source/Cosmos.Core_Plugs/Runtime/Intrinsics/X86/LzcntImpl.cs, source/Cosmos.Core_Plugs/Runtime/Intrinsics/X86/X86Base.cs
Fix Byte.ToString("X")
Add more byte tests
=> Add plugs to disable intrinsics

Tests/Cosmos.TestRunner.TestController/Assert.cs, Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/System/MathTest.cs, source/Cosmos.Core_Plugs/MathImpl.cs, source/Cosmos.System2_Plugs/System/MathImpl.cs
Use x86 fpu instructions to calculate sine and cosine
Required https://github.com/CosmosOS/XSharp/pull/57
=> Optimise trig operations

source/Cosmos.Build.Builder/Cosmos.Build.Builder.csproj, source/Cosmos.Build.Builder/Services/HasteBinClient.cs, source/Cosmos.Build.Builder/ViewModels/MainWindowViewModel.cs, source/Cosmos.Build.Builder/Views/MainWindow.xaml, source/Cosmos.Build.Builder/Views/MessageBox.xaml.cs
Did the up for grabs for [Builder Pastebin integration](https://github.com/CosmosOS/Cosmos/issues/2166)
Had to use hastebin instead, pastebin requires dev key
=> Added paste support to hastebin for the log

source/Cosmos.System2/Graphics/Canvas.cs
Currently, Canvas.DrawImageAlpha always creates a new Pen. For every pixel. This PR changes it so that there is one Pen, created at the beginning of the method. Each pixel just changes the color, which improves performance. My kernel with ~15 alpha images went from 15 fps to 24 fps
=> Improve DrawImageAlpha to not use a new Pen every time

source/Cosmos.Build.Tasks/CreateGrubConfig.cs, source/Cosmos.Build.Tasks/Gzip.cs, source/Cosmos.Build.Tasks/build/Cosmos.Build.targets, source/Cosmos.VS.ProjectSystem/BuildSystem/Rules/CosmosPropertyPage.xaml
This PR adds an option to compress the kernel binary using gzip, reducing the ISO size (by around 80%, on average.)
To use:
- Open a Cosmos project's properties.
- Set Compression to gzip.
Requires https://github.com/CosmosOS/Common/pull/9
=> Add kernel compression

source/Cosmos.HAL2/Drivers/PCI/Video/VMWareSVGAII.cs
This PR fixes following issue: https://github.com/CosmosOS/Cosmos/issues/2391
Every other canvas seems to always use the correct offset.
=> Fix SVGAII GetPixel

Makefile
found a bug in your makefile in regards to .net 6. the output folder was changed to net6.0, so I updated your makefile to use any folder name, as well as clean beforehand so that there will be only one output folder.
=> fix directory not found when using .net 6

source/Cosmos.HAL2/PIT.cs
This PR adds minor improvements to the PIT:
- minor formatting changes
- added documentation
- ability to read the CPU state when the timer interrupt has occurred, allowing for things like basic preemptive multitasking
- timeouts changed from signed 32-bit integers to unsigned 64-bit integers, allowing for higher delays between each timer cycle
=> Minor PIT improvements

Docs/articles/Installation/DevKit.md
This adds Mkisofs to the list of prerequisites on the Linux installation section of the dev-kit page.
=> Add mkisofs to prerequisites on installation docs page

source/Cosmos.Build.Tasks/Nasm.cs, source/Cosmos.Build.Tasks/build/Cosmos.Build.targets, source/Cosmos.VS.ProjectSystem/BuildSystem/Rules/CosmosPropertyPage.xaml
I've added the ability to use compiler optimizations. This may have performance increases.
Available optimization modes:
* O0 (No optimizations)
* O1 (Minor optimizations)
* O2 (Decent optimizations; May be the most stable)
* O3 (Major optimizations; may be unstable)
* Os (Optimize for the smallest possible code size; May be unstable)
* Ofast (Optimize for code speed; May be unstable)
=> Added compiler optimizations

source/Cosmos.Build.Tasks/CreateGrubConfig.cs, source/Cosmos.Build.Tasks/build/Cosmos.Build.targets, source/Cosmos.VS.ProjectSystem/BuildSystem/Rules/CosmosPropertyPage.xaml
I've added the option to change the GRUB boot timeout because I think it could be useful during debugging. If the value isn't set it will default to 0 seconds.
=> Add option to set GRUB boot timeout

source/Cosmos.HAL2/Drivers/PCI/Video/VMWareSVGAII.cs
Fixes #1484
This PR fixes the SetCursor() function and adds a new DefineAlphaCursor() to define a cursor using an image.
Note that the code has been taken from https://github.com/Project-Sphere/SphereOS/blob/master/SphereOS/Core/Drivers/VMWareSVGAII.cs.
=> Fix VMware SVGA II cursor

Tests/Kernels/Cosmos.Kernel.Tests.Fat/System.IO/DirectoryTest.cs
Fixes #747
This PR adds a simple test for creating a directory with a dot in the name.
=> Add FAT test for a directory with dot

source/Cosmos.Build.Tasks/IL2CPU.cs, source/Cosmos.Build.Tasks/build/Cosmos.Build.targets, source/Cosmos.VS.ProjectSystem/BuildSystem/Rules/CosmosPropertyPage.xaml
This PR adds a new option in the project properties to allow X# comments. By default, it is disabled for faster compile times.
=> Include X# comments option in properties

source/Cosmos.Debug.Hosts/VMware.cs
Fixes #2259
This PR makes it so that VMware Workstation is properly closed from the debug engine. This is done by comparing the number of vmware-vmx.exe processes before and after the VM is launched. It then gets the vmware-vmx processes launched alongside the VM, and adds them to a list, which then the debug engine uses to kill those running processes when it stops.
This is not a perfect solution (another VM could be launched at the exact same time as Cosmos and still be detected by the debug engine), but this is much better than just killing every single vmware-vmx process.
=> Close VMware Workstation properly from debug engine

Docs/articles/Kernel/ManifestResouceStream.md
The PR #1993 removed NASM and replaced it by YASM which does not seem to cause this problem anymore, which makes that section irrelevant.
=> Update ManifestResouceStream.md to remove the Drawback section

Docs/articles/Kernel/OnBoot.md, Docs/articles/Kernel/Startup.md
This PR updates the OnBoot.md and Startup.md documentation to improve clarity and accuracy.
In OnBoot.md, the example has been fixed and the switchable option list has been separated into separate code blocks for better readability.
In Startup.md, the documentation has been revamped to provide more detail on the boot process. There is also some words added about the BIOS and bootloader. The Sys.Kernel.Start() method has also been explained in greater detail, including a "What does it do?" section and an "Overriding it" section. Additionally, code blocks have been added where necessary to improve readability.
=> Made OnBoot.md a bit more detailed, and Startup.md alot more detailed.

source/Cosmos.Build.Tasks/CreateLimineConfig.cs, source/Cosmos.System2/Audio/IO/MemoryAudioStream.cs
The previous changes in `MemoryAudioStream.cs` caused some compilation errors on Linux due to some syntax that was too new or unsupported. The grammar errors were visible in Limine when an operating system was booting.
=> Revert some changes in MemoryAudioStream.cs and fix limine grammar errors

Docs/articles/Kernel/Startup.md
All this PR does is change this section in Startup.md:
>  First, it checks if `System.String.Empty` was not... Uhh, thrown away by the compiler.
Into this:
> First, it checks if `System.String.Empty` is null. If it is null, then it will just throw an exception. If it isn't, it just continues.
This is to make the documentation a bit more formal.
=> Made Startup.md a bit more formal in the String.Empty section

Docs/articles/Kernel/CGS.md
It still created a pen, also added that the code is meant for devkit and not userkit
=> Fix canvas docs article

source/Cosmos.System2_Plugs/System/ConsoleImpl.cs
Before, if you would pass an object to Console.Write or Console.WriteLine without converting it to a string, it would hang the system and output a mess of a color fest (at least in my case).
This was easily fixed by calling ToString on the object, which makes the Write (and WriteLine) method behave as it should.
=> Convert object to string in ConsoleImpl.Write(object) and ConsoleImpl.WriteLine(object)

source/Cosmos.System2/FileSystem/Disk.cs, source/Cosmos.System2/FileSystem/ISO9660/ISO9660FileSystem.cs
Fixes ISO9660
It was caused by the VFSManager looking for partitions, but on a CD there usually are no partitions. So I just made CDs act like one big partition and this fixed the problem
=> Fix ISO9660

Docs/articles/GettingStarted.md
VMWare -> VMware
Seeing VMWare with the 3rd letter capitalized made my eyes hurt, so I fixed it with a simple CTRL + H
=> Change how VMware is referenced in the docs

source/Cosmos.Build.Tasks/Cosmos.Build.Tasks.csproj
Changing it to x86 seems to have broken the devkit.
=> Fix Cosmos.Build.Tasks target

source/Cosmos.Build.Builder/packages.lock.json, source/Cosmos.Build.Tasks/packages.lock.json, source/Cosmos.Deploy.Pixie/Cosmos.Deploy.Pixie.csproj, source/Cosmos.Deploy.Pixie/packages.lock.json, source/Cosmos.Deploy.USB/Cosmos.Deploy.USB.csproj, source/Cosmos.Deploy.USB/packages.lock.json, source/Cosmos.VS.DebugEngine/Cosmos.VS.DebugEngine.csproj, source/Cosmos.VS.DebugEngine/packages.lock.json, source/Cosmos.VS.ProjectSystem/Cosmos.VS.ProjectSystem.csproj, source/Cosmos.VS.ProjectSystem/packages.lock.json, source/Cosmos.VS.Windows/Cosmos.VS.Windows.csproj, source/Cosmos.VS.Windows/packages.lock.json
Statement copied from cosmos dev-general:
An error appeared in latest cosmos with latest visual studio update and i point my figures back to a commit which involved changing many win-x64 to win-x86 causing president problems, the thread is here ⁠[...] changes to fix this bug include;
`
Build.Sln\
source/Cosmos.Deploy.Pixie/Cosmos.Deploy.Pixie.csproj - revert win-x86 back to win-x64 inside of RuntimeIdentifier
source/Cosmos.Deploy.USB/Cosmos.Deploy.USB.csproj - revert win-x86 back to win-x64 inside of RuntimeIdentifier
source/Cosmos.VS.DebugEngine/Cosmos.VS.DebugEngine.csproj - revert win-x86 back to win-x64 inside of RuntimeIdentifier
source/Cosmos.VS.ProjectSystem/Cosmos.VS.ProjectSystem.csproj - revert win-x86 back to win-x64 inside of RuntimeIdentifier …
=> Fix cosmos build and recongition error

Docs/articles/Kernel/MemoryManagement.md, Tests/Kernels/Cosmos.Compiler.Tests.TypeSystem/Kernel.cs, source/Cosmos.Core/Memory/HeapSmall.cs, source/Cosmos.Core/Memory/RAT.cs
Add new HeapSmall.PruneSMT method with tests and documentation
This allows the user to prune useless pages from the SMT, if it has grown too much
=> Add HeapSmall.PruneSMT

source/Cosmos.Build.Tasks/MakeIso.cs, source/Cosmos.HAL2/BlockDevice/ATAPI.cs, source/Cosmos.System2/FileSystem/Disk.cs, source/Cosmos.System2/FileSystem/ManagedPartition.cs
- ISO9660 somehow got detected as FAT FS since UEFI support was added
- There is no block count on ATAPI devices (? not sure why that is), instead we just put a large number there. Its read only anyways.
- Xorriso somehow changed and output all file names as UPPERCASE. Adding -allow-lowercase made it go back to what it did before.
=> Fix ISO9660 support

Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/System/Int32Test.cs, source/Cosmos.System2_Plugs/System/Int32Impl.cs
Improved Hexadecimal format code as it was changing the value of the original variable (tested only on [SharpLab](https://sharplab.io/), since I did the change before testing on Cosmos, but I assume that if it was changing on normal C# context, then it should have been changing on Cosmos too), also added support for the decimal format and padding.
=> Updates on int.ToString(`format`)

source/Cosmos.HAL2/PS2Mouse.cs, source/Cosmos.System2/MouseManager.cs
Scrolling wasnt supported in the MouseManager and the PS/2 implementation didnt implement it properly either
=> Support scrolling properly

Docs/articles/Installation/DevKit.md, Docs/articles/Installation/UserKit.md, Docs/articles/toc.md, Docs/docfx.json, Docs/index.md, Docs/install.md, Docs/toc.yml
im going to split up "API Documentation" so it not just every thing
- Cosmos
- Plugs
- XSharp
- IL2CPU
- tool/build system
clean up install info pages
add public xref link
=> working on docs to make it a bit more useable

source/Cosmos.Debug.Hosts/VMware.cs
VMWare sometimes can take more than 15s to attach. This PR gives it more time.
=> Give VMWare more time to attach

README.md
With the recent changes the FS is a pretty stable and decently fast, so imo these notes should be removed.
=> Remove FS warnings from README

source/Cosmos.Build.Tasks/MakeIso.cs, source/Cosmos.Build.Tasks/build/Cosmos.Build.targets, source/Cosmos.VS.ProjectSystem/BuildSystem/Rules/CosmosPropertyPage.xaml
Users can choose if they want to compile their OS with UEFI support.
=> Add UEFI toggle to project properties

Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/Kernel.cs, Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/System/ActivatorTests.cs, source/Cosmos.Core_Plugs/System/ActivatorImpl.cs
This PR add the plugs for `System.Activator.CreateInstance<T>()` and `System.Activator.CreateInstance(Type T, bool, bool)` two methods that are used to create generic types.
With  `System.Activator.CreateInstance<T>()` the following start to work on cosmos:
```csharp
// A generic method to get an instance of type T
public static T Get<T>() where T : class, new()
{
return new T();
}
```
1. **Constructors may not be on the compilation result**:At the moment Constructors, as any other method, are not included on the compilation result if never called, this could cause stack corruption or null reference exceptions when calling one of these methods or when using its result.
To avoid this, you would need to add a `dummy` variable somewhere (`BeforeRun` recommended) to make IL2CPU include the …
=> Plugged `System.Activator.CreateInstance` methods for types with parameterless constructors.

Docs/articles/Changelog.md, Docs/articles/Compiler/il2cpu.md, Docs/articles/Debugger/DebugCommands.md, Docs/articles/GettingStarted.md, Docs/articles/Installation/DevKit.md, Docs/articles/Installation/Running.md, Docs/articles/Installation/UserKit.md, Docs/articles/Kernel/Audio.md, Docs/articles/Kernel/CGS.md, Docs/articles/Kernel/Levels.md, Docs/articles/Kernel/ManifestResouceStream.md, Docs/articles/Kernel/MemoryManagement.md, Docs/articles/Kernel/Network.md, Docs/articles/Kernel/OnBoot.md, Docs/articles/Kernel/Plugs.md, Docs/articles/Kernel/Startup.md, Docs/articles/Kernel/VFS.md, Docs/articles/Reference/x86.md, Docs/articles/Tests/TestRunner.md, Docs/index.md
This should clean majority of the documentation on cosmosos.github.io to ensure clarity and for it to be up-to-date. Some articles (like the Levels.md) aren't touched because they are quite old.
=> Adjust COSMOS documentation

Makefile
Dotnet seems to be updated and doesn't support `dotnet new install` but rather shows to be using `dotnet new -i` so that's what I changed in the Makefile, it works now!
=> Makefile short fix

source/Cosmos.HAL2/Drivers/Video/SVGAII/VMWareSVGAII.cs, source/Cosmos.System2/Graphics/Canvas.cs, source/Cosmos.System2/Graphics/SVGAIICanvas.cs, source/Cosmos.System2/Graphics/VBECanvas.cs, source/Cosmos.System2/Graphics/VGACanvas.cs
All changes
-Fixed VBE positioning bug issue #3009 
-SVGAII & VBE - The bug with things going off screen has been fixed
-SVGAII - Fixed draw filled rectangles going also off screen. it was already fixed in vbe.
Warning: fixing off screen left side will be added in part 2 unless someone wants to do it first ;p
=> CGS Update (part 1)

Makefile
This pull request fixes typos that made the makefile unusable
=> Fix MakeFile typos

Docs/articles/Kernel/Plugs.md
I generally try to avoid trivially small pull requests, but seeing as this typo cost me quite a bit of time I figured I'd try to save others from the same headache.
=> Changed `PlugReference` to `PlugsReference`

Tests/Kernels/GraphicTest/Kernel.cs, source/Cosmos.Core/ManagedMemoryBlock.cs, source/Cosmos.Core/MemoryBlock.cs, source/Cosmos.HAL2/Drivers/Video/VBEDriver.cs, source/Cosmos.System2/Graphics/Canvas.cs, source/Cosmos.System2/Graphics/FullScreenCanvas.cs, source/Cosmos.System2/Graphics/SVGAIICanvas.cs, source/Cosmos.System2/Graphics/VBECanvas.cs, source/Cosmos.System2/Graphics/VGACanvas.cs
This time nice and clean!
Added 
- GetImage (SVGAII & VBE)
- DrawCroppedImage (You can now draw wallpaper cropped by your taskbar height!)
- DrawPoint (int)
- GetRawPoint
- DrawRectangle has been improved
- More draw array functions - for int[] (just copying to video buffer!)
- MANY VBE Bugfixes
- GetImage tests
- Finished preventOffBoundPixels (now its working for left side and right side - finished part of CGS Update part 1)
Note: I didn't add XML to the override voids, as the others don't have them either. XML comments are always above virtual/abstract voids. Writing this because of my last pr hihi
=> ✨CGS Update part 2 (Remastered)

LICENSE.txt, Setup/Cosmos.iss
=> Update license year
