CosmosOS/Cosmos

- source/Cosmos.IL2CPU.Tests/Cosmos.IL2CPU.Tests.csproj
- source/Cosmos.IL2CPU.Tests/Plugs/System/BufferTests.cs
- source/Cosmos.IL2CPU.Tests/Properties/AssemblyInfo.cs
- source/Cosmos.IL2CPU/ILOpCodes/OpSwitch.cs
- source/Cosmos.IL2CPU/Plugs/System/Buffer.cs
- source/Cosmos.sln
> Add plug for Buffer.__Mmmove on the .NET 4.6

- source/MPF/10.0/Src/CSharp/ProjectReferenceNode.cs
See #10 
This is fix the bug in the MPF https://mpfproj11.codeplex.com/workitem/1466
> Fix resolution of references inside solution folder.

- source/Cosmos.IL2CPU/ILOpCodes/OpType.cs
> Added Ldobj OpType

- Setup/Code.inc
- Setup/Cosmos.iss
- Setup/Events.inc
- source/Cosmos.Debug.VSDebugEngine/AD7.Impl/AD7Engine.cs
Current GUID was conflicting with existing tools and a lot of examples on the Internet
Relates to #51
> Changed GUID for debug engine

- source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
> Added Localloc opcode

- Tests/Cosmos.Compiler.TestsBase/CompilerRunner.cs
- Users/Matthijs/DebugCompiler/Program.TestCompiler.cs
- source/Cosmos.Assembler/ElementReference.cs
- source/Cosmos.Assembler/Instruction.cs
- source/Cosmos.Assembler/LabelName.cs
- source/Cosmos.Build.MSBuild/ExtractMapFromElfFile.cs
- source/Cosmos.Build.MSBuild/ReadNAsmMapToDebugInfo.cs
- source/Cosmos.Debug.Common/Cosmos.Debug.Common.csproj
- source/Cosmos.Debug.Common/DebugInfo.cs
- source/Cosmos.Debug.Common/DebugModel.cs
- source/Cosmos.Debug.Common/ObjDump.cs
- source/Cosmos.Debug.Common/SQL.cs
- source/Cosmos.Debug.Common/SQLite.sql
- source/Cosmos.Debug.Common/SQLiteIndexes.sql
- source/Cosmos.Debug.VSDebugEngine/AD7.Impl/AD7PendingBreakpoint.cs
- source/Cosmos.IL2CPU.Profiler/Assembler.cs
- source/Cosmos.IL2CPU.Profiler/Program.cs
- source/Cosmos.IL2CPU/AppAssembler.cs
- source/Cosmos.IL2CPU/CompilerEngine.cs
- source/Cosmos.sln
- source/ElfMap2DebugDb/App.config
- source/ElfMap2DebugDb/ElfMap2DebugDb.csproj
- source/ElfMap2DebugDb/Program.cs
- source/ElfMap2DebugDb/Properties/AssemblyInfo.cs
Add some speed improvements for compilation process.
For discussion see #9
> Compilation improvements.

- Docs/Articles/MS5/index.md
- Docs/Directories.md
- Docs/Installation/DevKit.md
- readme.md
I've edited some docs and fixed up a mistake in the readme.md file. @mterwoord
> Edited Some Docs

- Tests/Cosmos.Common.Tests/.editorconfig
- Tests/Cosmos.Common.Tests/Cosmos.Common.Tests.csproj
- Tests/Cosmos.Common.Tests/Properties/AssemblyInfo.cs
- Tests/Cosmos.Common.Tests/ToHexStringTest.cs
- source/Cosmos.Common/Cosmos.Common.csproj
- source/Cosmos.Common/NumberHelper.cs
- source/Cosmos.Core/Heap.cs
- source/Cosmos.Debug.Common/DebugInfo.cs
- source/Cosmos.HAL/PciDevice.cs
- source/Cosmos.IL2CPU/GCImplementation.cs
- source/Cosmos.sln
There some code cleanup and removed duplicates. Some tests added to test these fixes
> Code cleanup

- source/Cosmos.System/VGAScreen.cs
VGAScreen is now working.
Note: You must use Cosmos.System.VGAScreen class, instead of Cosmos.HAL.VGAScreen class.
> VGAScreen fix

- source/Cosmos.IL2CPU/ILScanner.cs
I updated links for github in ILScanner.cs
> Update links for github

- source/Cosmos.HAL/Drivers/VBEDriver.cs
- source/Cosmos.System/VBEScreen.cs
all that remains now is nice to have features but this can come at later stage.
> Completed the VBE driver

- Setup/Cosmos.iss
Update XSC.exe location from "{app}\Build\Tools\" to "{app}\Build\IL2CPU\" to fix icons not displaying
> Fixes #168

- readme.md
- Added some badges with repo stats.
- Added Gitter to the `Joining Cosmos` section
> Added badges and Gitter notes

- source/XSharp.VS/Guids.cs
- source/XSharp.VS/LanguageService.cs
Fix LanguageService Syntax Highlighting
> Fixes #158

- source/Cosmos.Build.Common/BuildProperties.cs
> Fixed Bug on Debug

- Tests/Cosmos.TestRunner.Core/DefaultEngineConfiguration.cs
Fixed some spelling mistakes and added some comments for un-documented
lines
> Comments Update in TestRunner Config

- source/Cosmos.Build.Installer/Task.cs
This fixes unhandled exceptions from non-ui thread. Exception messages are now added to log list.
> installer unhandled crash issue fixed

- source/Cosmos.HAL/Drivers/VGAScreen.cs
- source/Cosmos.System/VGAScreen.cs
VGAScreen is fixed and both 640x480, 320x200 and 720x480 modes working now.
@mterwoord
> VGAScreen 640x480 and 720x480 is working now

- Tests/Cosmos.Compiler.Tests.MultidimensionalArrays/AssemblyInfo.cs
- Tests/Cosmos.Compiler.Tests.MultidimensionalArrays/Compiler.Tests.MultidimensionalArraysBoot.Cosmos
- Tests/Cosmos.Compiler.Tests.MultidimensionalArrays/Cosmos.Compiler.Tests.MultidimensionalArrays.csproj
- Tests/Cosmos.Compiler.Tests.MultidimensionalArrays/Kernel.cs
Test for multidimensional arrays.
> Bug hunting.

- Docs/Kernel/Levels.md
Updated levels.md to have tutorial and better docs
> Update to levels.md

- source/Cosmos.Build.Builder/CosmosTask.cs
Fixed the check for inno setup.
> chg: fix pre requisit for setup program

- source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
> fixing #254

- source/Cosmos.Core/MemoryBlock.cs
- source/Cosmos.HAL/TextScreen.cs
- In MemoryBlock added Fill overloads that accept UInt16
- In TextScreen removed unused variables, magic number and finally the
Clear() method does what is expected!
> Console modifications

- source/Cosmos.System/Console.cs
> Fixed #313

- Tests/Cosmos.Kernel.Tests.Fat/Kernel.cs
- source/Cosmos.System.Plugs/System/IO/FileImpl.cs
- source/Cosmos.System.Plugs/System/IO/FileStreamImpl.cs
- source/Cosmos.System/FileSystem/FAT/FatStream.cs
- Added test to write another file in the same directory
- Added test for new method WriteAllLines()
- Added test for method WriteAllBytes() / ReadAllBytes()
- Added tests to create files in a subdirectory
- Added utility method byteArrayAreEquals()
> Added new (failing) tests on FAT

- install-VS2015.bat
> Added two messages :
* For the build completed successfuly
* For the Cosmos Builder Tool does not exists
> Updated the install-VS2015.bat file

- Tests/Cosmos.Compiler.Tests.Exceptions/Kernel.cs
- Updated test runner to include exception filtering tests
> Updated Exceptions test runner

- Docs/Directories.md
> Replaced 'folder' to 'directory'
> Replaced some words to correct words
> Updated the directories.md file

- readme.md
> Correction of some like-'robot' texts
> Updating the readme.md file

- Tests/Cosmos.Compiler.Tests.Bcl/Cosmos.Compiler.Tests.Bcl.csproj
- Tests/Cosmos.Compiler.Tests.Bcl/Kernel.cs
- Tests/Cosmos.Compiler.Tests.Bcl/System/BitConverterTest.cs
- Tests/Cosmos.Compiler.Tests.Bcl/System/Int64Test.cs
- Tests/Cosmos.Compiler.Tests.Bcl/System/UInt64Test.cs
- Added Bitconverter tests (fails for Double)
- Added to tests of Long and Ulong conversion between them
> - Added Bitconverter tests (fails for Double)

- Tests/Cosmos.Kernel.Tests.Fat/Kernel.cs
- Tests/Cosmos.TestRunner.Core/TestKernelSets.cs
- source/Cosmos.Common/Extensions/ByteConverter.cs
- source/Cosmos.IL2CPU/IL/Newobj.cs
- source/Cosmos.System.Plugs/System/IO/DirectoryInfoImpl.cs
- source/Cosmos.System/FileSystem/CosmosVFS.cs
- source/Cosmos.System/FileSystem/FAT/Listing/FatDiretoryEntry.cs
- Fixed Newobj for string with length parameter.
- Minor changes in debugging and FAT test messages.
- Removed useless "if" in FAT, previously added by me.
EDIT: I couldn't fix the bug in DirectoryEntry creation.
EDIT: Fixes #476
> Fix Newobj for string and minor changes

- Tests/Cosmos.Compiler.Tests.Bcl/System/ObjectTests.cs
- source/Cosmos.Core.Plugs/System/ObjectImpl.cs
- source/Cosmos.IL2CPU/IL/Castclass.cs
- source/Cosmos.IL2CPU/IL/Newobj.cs
- source/Cosmos.IL2CPU/VTablesImpl.Debug.cs
- source/Cosmos.IL2CPU/VTablesImpl.cs
- Fix MemberwiseClone.
- Fix object sizes in Newobj.
- Minor changes in Castclass and VTablesImpl.
EDIT: Fixes #482
> Fix MemberwiseClone

- Tests/Cosmos.Kernel.Tests.Fat/Kernel.cs
- source/Cosmos.Common/Extensions/ToHexString.cs
- source/Cosmos.System/FileSystem/FAT/Listing/FatDiretoryEntry.cs
- Fix FAT test.
- Minor changes in ToHexString and the FAT test.
> Fix FAT Test and Minor Changes

- Docs/Directories.md
> Fixed some typos in the docs

- source/Cosmos.System/Keyboard/ConsoleKeyExExtensions.cs
That fixes "KeyEx not implemented!" with keys "0123456789*-+/. WinLeft and WinRight".
> Added some new Console keys #2

- Demos/Cosmos Graphic Subsytem/Kernel.cs
- Tests/Cosmos.TestRunner.Core/TestKernelSets.cs
- Tests/GraphicTest/Kernel.cs
- source/Cosmos.System/Graphics/Canvas.cs
Fulfills #603 
Implemented the following functions:
```
public void DrawLine(Pen pen, Point p1, Point p2)
public virtual void DrawCircle(Pen pen, int x_center, int y_center, int radius)
public virtual void DrawEllipse(Pen pen, int x_center, int y_center, int x_radius, int y_radius)
public virtual void DrawPolygon(Pen pen, PointsCollection points)
```
The `DrawLine()` function is just a wrapper on the existing one, it doesn't need to be virtual.
Implemented the following classes:
```
public class Cosmos.System.Graphics.Point
public class Cosmos.System.Graphics.PointsCollection
```
> Implemented additional drawing function as per issue #603

- readme.md
Moved links to their respective sections on the website, made new pages for Cosmos in the media, updated links and more
I've also made two new pages on the website [Cosmos in the media](http://www.gocosmos.org/inthemedia/) & [Cosmos resources](http://gocosmos.org/resources) and updated various pages such as [Cosmos News](http://www.gocosmos.org/news/) and [Cosmos Documentation](http://www.gocosmos.org/docs/) so the website is a better place to go to for more information and to learn more about Cosmos
> Updated information across website and readme, moving links etc.

- Tests/Cosmos.Compiler.Tests.Bcl/Helper/EqualityHelper.cs
- Tests/Cosmos.Compiler.Tests.Bcl/Kernel.cs
- Tests/Cosmos.Compiler.Tests.Bcl/System/DoubleTest.cs
- Tests/Cosmos.Compiler.Tests.Bcl/System/MathTest.cs
- source/Cosmos.System_Plugs/System/MathImpl.cs
Using Newton Method and a good square root approximation to improve the Math.Sqrt() speed.
> Improve Math.Sqrt() implementation.

- source/Cosmos.System/Console.cs
I think this is a bad way to do it, but it works ... What do you think @fanoI ?
> Extended ASCII characters.

- source/Cosmos.Common/Extensions/ByteConverter.cs
- source/Cosmos.System2/FileSystem/CosmosVFS.cs
- source/Cosmos.System2/FileSystem/FAT/FatFileSystem.cs
- source/Cosmos.System2/FileSystem/FAT/FatStream.cs
- source/Cosmos.System2/FileSystem/FAT/Listing/FatDirectoryEntryMetadata.cs
- source/Cosmos.System2/FileSystem/FAT/Listing/FatDiretoryEntry.cs
- source/Cosmos.System2/FileSystem/Listing/DirectoryEntry.cs
- source/Cosmos.System2/FileSystem/VFS/VFSManager.cs
- source/Cosmos.System2_Plugs/System/IO/FileStreamImpl.cs
All of this is @jp2masa's work.
It's taken from https://github.com/CosmosOS/Cosmos/pull/522.
All works.
- Fix FAT directory entry allocation and directory listing.
- Re-enabled FileStream old constructor code, fixing FatStream, which didn't let it work.
> FileSystem fixes.

- source/Cosmos.System2/FileSystem/CosmosVFS.cs
- source/Cosmos.System2/FileSystem/FAT/FatFileSystem.cs
- source/Cosmos.System2/FileSystem/FAT/Listing/FatDiretoryEntry.cs
- source/Cosmos.System2/FileSystem/FileSystem.cs
- source/Cosmos.System2/FileSystem/Listing/DirectoryEntry.cs
Now mSize in GetVolumes works and won't return 0.
> mSize in GetVolumes fix.

- source/Cosmos.Build.MSBuild/Cosmos.targets
This fixes the commit with the last userkit where a few lines needed to be added to Cosmos.targets
This pull request fixes this issue by adding it to the source before being compiled into a userkit for a release
> Fixed Cosmos.targets for new user kit

- source/Cosmos.System2/Console.cs
Reverts CosmosOS/Cosmos#718
Issues regarding writing to the Console, nothing printed out using Write or WriteLine appears, yet input is still visible, something to do with the Extended ASCII pr, tried fixing to no avail. For now, I think it needs some changes to ensure it works.
> Revert "might make console faster"

- Setup/Cosmos.iss
If the user is not admin, this allows the user to change the install place to his user's appdata. This fixes the problem I had.
> Allows user to change install directory

- NuGet.config
- Tests/Cosmos.TestRunner.UI.Avalonia/App.xaml
- Tests/Cosmos.TestRunner.UI.Avalonia/App.xaml.cs
- Tests/Cosmos.TestRunner.UI.Avalonia/Cosmos.TestRunner.UI.Avalonia.csproj
- Tests/Cosmos.TestRunner.UI.Avalonia/ViewModels/MainWindowViewModel.cs
- Tests/Cosmos.TestRunner.UI.Avalonia/ViewModels/SettingsDialogViewModel.cs
- Tests/Cosmos.TestRunner.UI.Avalonia/Views/MainWindow.xaml
- Tests/Cosmos.TestRunner.UI.Avalonia/Views/MainWindow.xaml.cs
- Tests/Cosmos.TestRunner.UI.Avalonia/Views/SettingsDialog.xaml
- Tests/Cosmos.TestRunner.UI.Avalonia/Views/SettingsDialog.xaml.cs
- Added a test runner UI, built on Avalonia (it's pre-release and beta1 will be released soon, but that's not a problem, as the test runner UI is not part of the final product).
> Added a test runner UI, built on Avalonia

- Tests/BoxingTests/Kernel.cs
- Tests/Cosmos.TestRunner.Core/TestKernelSets.cs
- Fixed and reenabled boxing tests.
> Tests for CosmosOS/IL2CPU#39

- source/Cosmos.System2/FileSystem/CosmosVFS.cs
Pull request originally from #838, downstream repo was deleted so in case work needs done (which it might, might not), this will be easier to work with.
Might be ready to merge straight away, if no one's checked it, I'll check it out later.
> PR #838 Fix finding one volume

- Tests/Cosmos.Compiler.Tests.Bcl/System/MathTest.cs
- source/Cosmos.System2_Plugs/System/MathImpl.cs
The new implementation should be able to be used for numbers larger than an int.
> New Implementation for Math.Ceiling

- Tests/Cosmos.Compiler.Tests.Bcl/Kernel.cs
- Tests/Cosmos.Compiler.Tests.Bcl/System/ConvertTests.cs
- source/Cosmos.System2_Plugs/System/DecimalImpl.cs
- source/Cosmos.System2_Plugs/System/Int32Impl.cs
Fixes #282
- Added tests for Convert.
- Added back plugs for Decimal.
- Plugged Int32.ToString(IFormatProvider).
> Fixed Convert and added tests

- .editorconfig
Please discuss these rules, including their severity.
- Added code style rules.
> Added code style rules

- Tests/Cosmos.TestRunner.TestController/Assert.cs
- Added assert location to failed asserts message.
> Added assert location to failed asserts message

- Tests/Cosmos.Compiler.Tests.Bcl/System/Int64Test.cs
- appveyor.yml
- Added tests for div and rem for int64 operands.
> Added tests for div and rem for int64 operands

- Tests/Cosmos.Compiler.Tests.Bcl/System/StringTest.cs
- source/Cosmos.Core_Plugs/System/StringImpl.cs
This should fix the issue described in #943.
A test has been added.
The last pull request had too many commits so I opened a new one
> Fixed String Replace (Issue 943)

- source/Cosmos.System2/Graphics/Bitmap.cs
If other color types should be supported I can also try to add them.
> [CGS] Add support for 24 bit bitmaps

- Tests/BoxingTests/Kernel.cs
- Tests/SimpleStructsAndArraysTest/Kernel.cs
- source/Cosmos.System2_Plugs/System/ConvertImpl.cs
- Uncommented structs tests.
- Added plug for `Convert.ToString(long, int)`.
> Tests for structs

- source/Cosmos.Core/PIC.cs
- source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs
- source/Cosmos.HAL2/PCI.cs
- source/Cosmos.HAL2/PCIDevice.cs
This fixes https://github.com/CosmosOS/Cosmos/issues/926.
> PCNETII Driver now working again.

- Tests/Cosmos.Compiler.Tests.TypeSystem/Kernel.cs
- Added tests for CosmosOS/IL2CPU#44.
> Added type system tests

- Tests/Cosmos.TestRunner.Core/Cosmos.TestRunner.Core.csproj
- Tests/Cosmos.TestRunner.Core/Engine.Bochs.cs
- Tests/Cosmos.TestRunner.Core/Engine.Helpers.cs
- Tests/Cosmos.TestRunner.Core/Engine.Run.cs
- Tests/Cosmos.TestRunner.Core/Engine.Running.cs
- Tests/Cosmos.TestRunner.Core/Engine.VMware.cs
- Tests/Cosmos.TestRunner.Core/Engine.cs
- Tests/Cosmos.TestRunner.Core/IKernelTestResult.cs
- Tests/Cosmos.TestRunner.Core/ITestResult.cs
- Tests/Cosmos.TestRunner.Core/KernelTestResult.cs
- Tests/Cosmos.TestRunner.Core/OutputHandlerBase.cs
- Tests/Cosmos.TestRunner.Core/OutputHandlerConsole.cs
- Tests/Cosmos.TestRunner.Core/OutputHandlerFullConsole.cs
- Tests/Cosmos.TestRunner.Core/RunConfiguration.cs
- Tests/Cosmos.TestRunner.Core/TestResult.cs
- Tests/Cosmos.TestRunner.Core/TestResultExtensions.cs
- Tests/Cosmos.TestRunner.Core/TestResultOutputHandler.cs
- Tests/Cosmos.TestRunner.UI.Avalonia/ViewModels/MainWindowViewModel.cs
- Tests/Cosmos.TestRunner.UI/MainWindow.xaml.cs
- Tests/Cosmos.TestRunner.UI/MainWindowHandler.TestEngine.cs
- Tests/Cosmos.TestRunner.UnitTest/KernelTests.cs
- Tests/Cosmos.TestRunner/Program.cs
> Test runner improvements

- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/Int64Test.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/UInt64Test.cs
- Added tests for 64-bit division.
> Added tests for 64-bit division

- Tests/Cosmos.TestRunner.Full/TestKernelSets.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Exceptions/Kernel.cs
- Tests/Kernels/Cosmos.Kernel.Tests.IO/Kernel.cs
- source/Cosmos.System2_Plugs/System/IO/FileStreamImpl.cs
Fixed MemoryStream tests, which are now enabled
Added plug for Stream GetByte
Added test for exceptions in using blocks
> Fixed IO Tests

- Tests/Cosmos.TestRunner.Core/Engine.Running.cs
- source/Cosmos.Core.DebugStub/CmdSend.xs
- source/Cosmos.Debug.DebugConnectors/CoreDump.cs
- source/Cosmos.Debug.DebugConnectors/DebugConnector.Receiving.cs
- source/Cosmos.Debug.DebugConnectors/DebugConnector.cs
- source/Cosmos.VS.DebugEngine/AD7.Impl/AD7Process.cs
- Fixed core dump.
- Fixed test runner core dump handler.
- Implemented debug engine core dump handler.
- Added `SendCoreDump` calls for null reference, stack corruption and stack overflow exceptions.
> Fixed core dump

- source/Cosmos.System2/Network/ARP/ARPPacket.cs
- source/Cosmos.System2/Network/EthernetPacket.cs
- source/Cosmos.System2/Network/IPv4/ARPPacket_Ethernet.cs
- source/Cosmos.System2/Network/IPv4/Config.cs
- source/Cosmos.System2/Network/IPv4/ICMPPacket.cs
- source/Cosmos.System2/Network/IPv4/IPPacket.cs
- source/Cosmos.System2/Network/IPv4/UDP/UDPPacket.cs
> Network code cleanup

- source/Cosmos.System2/Graphics/Canvas.cs
- source/Cosmos.System2/Graphics/FullScreenCanvas.cs
- source/Cosmos.System2/Graphics/SVGAIIScreen.cs
- source/Cosmos.System2/Graphics/VBEScreen.cs
> CGS code cleanup

- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/Collections/Generic/DictionaryTest.cs
- install-VS2019.bat
- source/Cosmos.Core_Plugs/System/Collections/Generic/ComparerHelpersImpl.cs
This PR in combination with a separate PR for IL2CPU resolves issue #584 .
>  Comparer Issue #584

- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/ArrayTests.cs
For https://github.com/CosmosOS/IL2CPU/pull/75
> Add tests for IndexOutOfRange exceptions

- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/ByteTest.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/Int16Test.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/Int32Test.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/Int64Test.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/SByteTest.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/UInt16Test.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/UInt32Test.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/UInt64Test.cs
For https://github.com/CosmosOS/IL2CPU/pull/77
> Added tests for checked conversions

- Tests/Kernels/Cosmos.Kernel.Tests.Fat/System.IO/DirectoryInfoTest.cs
So that the build works for now.
> Comment failing Filesystem Test

- source/Cosmos.System2/MouseManager.cs
> MouseManager fix

- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/Debug/DebugLaunchProvider.cs
Also stopped trying to launch debugger, since that wont work
Fixes #807 and #1314
> Fixed PXE launch path

- source/Cosmos.Core/ACPI.cs
- source/Cosmos.HAL2/BlockDevice/BlockDevice.cs
- source/Cosmos.HAL2/BlockDevice/Partition.cs
- source/Cosmos.HAL2/Drivers/PCI/Network/AMDPCNetII.cs
- source/Cosmos.HAL2/Drivers/PCI/Video/VMWareSVGAII.cs
- source/Cosmos.HAL2/Drivers/Video/VBEDriver.cs
- source/Cosmos.HAL2/Drivers/Video/VGAScreen.cs
- source/Cosmos.HAL2/Global.cs
- source/Cosmos.HAL2/KeyboardBase.cs
- source/Cosmos.HAL2/NetworkDevice.cs
- source/Cosmos.HAL2/PCI.cs
- source/Cosmos.HAL2/PCIDevice.cs
- source/Cosmos.HAL2/PCSpeaker.cs
- source/Cosmos.HAL2/PS2Keyboard.cs
- source/Cosmos.HAL2/Power.cs
- source/Cosmos.HAL2/TextScreen.cs
- source/Cosmos.HAL2/TextScreenBase.cs
Started working on Cosmos.HAL2 API docs
> [WIP] Hal api docs

- source/Cosmos.Core/ACPI.cs
- source/Cosmos.Core/BaseIOGroups.cs
- source/Cosmos.Core/CPU.cs
- source/Cosmos.Core/Global.cs
- source/Cosmos.Core/IOGroup/ATA.cs
- source/Cosmos.Core/IOGroup/PCSpeaker.cs
- source/Cosmos.Core/IOGroup/PIC.cs
- source/Cosmos.Core/IOGroup/PS2Controller.cs
- source/Cosmos.Core/IOGroup/RTC.cs
- source/Cosmos.Core/IOGroup/TextScreen.cs
- source/Cosmos.Core/IOGroup/VBE.cs
- source/Cosmos.Core/IOPort.cs
- source/Cosmos.Core/ManagedMemoryBlock.cs
- source/Cosmos.Core/MemoryBlock.cs
- source/Cosmos.Core/MemoryOperations.cs
- source/Cosmos.Core/PIC.cs
- source/Cosmos.Core/ProcessorInformation.cs
Started working on Cosmos.Core API docs
> [WIP] Core api docs

- source/Cosmos.Build.Builder/App.xaml.cs
Make additional builders close, when one is already open
> Fix builder not closing

- Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/Kernel.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl.System/System/GuidTest.cs
- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/Kernel.cs
> Merge guid.

- source/Cosmos.System2/Graphics/FullScreenCanvas.cs
- source/Cosmos.System2/Graphics/SVGAIICanvas.cs
- source/Cosmos.System2/Graphics/VBECanvas.cs
- source/Cosmos.System2/Graphics/VGACanvas.cs
Recent CGS update removed some XML comments, re-added those
> Re-added the Graphics documentation XML comments

- Docs/articles/Kernel/VFS.md
Updated the article so pictures will work on the site, and so it will be the same as on the wiki
> Updated VFS article

- source/Cosmos.VS.DebugEngine/AD7Util.cs
Fixes https://github.com/CosmosOS/Cosmos/issues/1334
> Made MessageBox always use UI thread

- Tests/Kernels/GraphicTest/Kernel.cs
- source/Cosmos.System2/Graphics/Canvas.cs
- source/Cosmos.System2/Graphics/Fonts/Font.cs
- source/Cosmos.System2/Graphics/Fonts/PCScreenFont.cs
> Basic DrawString and DrawChar with PC Screen Fonts (PSF)

- source/Cosmos.HAL2/Drivers/Video/VGADriver.cs
Closes https://github.com/CosmosOS/Cosmos/issues/1376
> Fix GetPointColor for VGA

- source/Cosmos.HAL2/Drivers/Video/VBEDriver.cs
- source/Cosmos.HAL2/PCIDevice.cs
- source/Cosmos.System2/Graphics/FullScreenCanvas.cs
https://github.com/CosmosOS/Cosmos/issues/1383
> VBE detection enhancement

- source/Cosmos.Core/CPU.cs
> CPU Vendor name fix

- Tests/Kernels/Cosmos.Compiler.Tests.Bcl/System/RandomTests.cs
- source/Cosmos.System2_Plugs/System/RandomImpl.cs
Random for now only used Second as seed, which makes it impossible to call often. 
Added tests to confirm that the fix works.
> Made Random return different values when called repeatedely

- Tests/Kernels/GraphicTest/Kernel.cs
- source/Cosmos.System2_Plugs/System/Drawing/ColorImpl.cs
> Color.FromName System.Drawing plug

- source/Cosmos.HAL2/PS2Controller.cs
Tested this on 3 Different Laptops from different brands, all touchpads worked without any issues
> Fix Laptop Touchpads

- Tests/Kernels/ProcessorTests/Kernel.cs
- source/Cosmos.Core/Bootstrap.cs
- source/Cosmos.Core/CPU.cs
- source/Cosmos.Core/MemoryOperations.cs
- source/Cosmos.Core/Multiboot.cs
- source/Cosmos.Core_Asm/MultibootImpl.cs
Fixed GetMBIAddress Plug
Cleaned up code
> Added CPU.GetMemoryMap

- source/Cosmos.Core/CPU.cs
> Update CPU.cs to fix a Typo

- source/Cosmos.VS.DebugEngine/AD7.Impl/AD7Process.cs
Fix path stored in debug info not being absolute and therefor looking in the wrong place
> Possible fix for cbd not being found

- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/OldCosmosPropertyPageControl.Designer.cs
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/OldCosmosPropertyPageControl.cs
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/OldPropertyManager.cs
> User defined launch configurations are loaded when reopening properties

- source/Cosmos.Core_Plugs/System/Threading/InterlockedImpl.cs
Should fix https://github.com/CosmosOS/Cosmos/issues/1562
> Add Interlocked.Add plug

- Setup/Cosmos.iss
- source/Cosmos.Build.Builder/BuildTasks/CreateSetupTask.cs
Inno Setup {userappdata} always points to C:\
Fix #1588
> Programatically get ApplicationData path

- readme-IT.md
> Create Readme - Add Italian version

- source/Cosmos.Build.Builder/Dependencies/InnoSetupDependency.cs
- source/Cosmos.Build.Builder/Dependencies/ReposDependency.cs
- source/Cosmos.Build.Builder/Dependencies/VisualStudioDependency.cs
- source/Cosmos.Build.Builder/Dependencies/VisualStudioWorkloadsDependency.cs
- source/Cosmos.Build.Builder/IDependency.cs
- source/Cosmos.Build.Builder/ViewModels/MainWindowViewModel.cs
Disable auto-install of workloads
Should fix issue #1603
> Disable auto-install of workloads

- source/Cosmos.HAL2/Drivers/Video/VBEDriver.cs
Reverts CosmosOS/Cosmos#1607
Turns out it wasnt finished
> Revert "Implement non linear framebuffer detection for VBE multiboot"

- source/Cosmos.Core_Plugs/System/Threading/InterlockedImpl.cs
- Adds most plugs for the Interlocked class.
> Add Interlocked plugs

- source/Cosmos.HAL2/Drivers/PCI/Network/RTL8139.cs
- source/Cosmos.HAL2/Network/NetworkInit.cs
Port over old RTL8139 driver and initialize it.
> Add RTL8139 updated driver

- Docs/articles/GettingStarted.md
- source/Templates/Cosmos.Templates.Kernel/content/Kernel-CSharp/Kernel.cs
- source/Templates/Cosmos.Templates.Kernel/content/Kernel-FSharp/Kernel.fs
- source/Templates/Cosmos.Templates.Kernel/content/Kernel-VisualBasic/Kernel.vb
Disambiguation for outdated guides on the internet. Though the changes are minor, they would have helped me so I'm hoping they will help others.
Corresponds with Issue #1740.
> Template Disambiguation with Documentation/Comments

- .github/workflows/stale.yml
Added additional label and exempt all milestone/assigned issues/prs
> Improved stale action

- Setup/Cosmos.iss
- source/Cosmos.HAL2/BlockDevice/AtaPio.cs
Fix ATA device model/firmware version/serial number decoding. With the fix these values are correct and not garbage.
Screenshot:
> Fix ATA Device name decoding

- README.md
> Fix hyperlink in readme

- README.md
> Add discord widget to readme

- source/Cosmos.System2/FileSystem/DiskManager.cs
I found this typo, so I decided to fork and fix it
> Fix typo in DiskManager.cs at 22:51

- source/Cosmos.System2/Network/IPv4/IPPacket.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPClient.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPPacket.cs
Send and receive data larger than 1500 bytes.
> [Net] Implement TCP packet sequencing

- source/Cosmos.System2/Network/IPv4/IPPacket.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPClient.cs
- Connect to an existing opened connection (SYN -> ACK)
- #1775 fix
> [Net] TCP Fixes

- Docs/articles/Kernel/Network.md
- source/Cosmos.System2/Helpers/ArrayHelper.cs
- source/Cosmos.System2/Network/IPv4/ICMPClient.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPClient.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPPacket.cs
- source/Cosmos.System2/Network/IPv4/TCP/Tcp.cs
- source/Cosmos.System2/Network/IPv4/TCP/TcpListener.cs
- source/Cosmos.System2/Network/IPv4/UDP/UdpClient.cs
https://github.com/CosmosOS/Cosmos/issues/1781
> Tcp Implementation

- source/Cosmos.Core/IOGroup/ATA.cs
- source/Cosmos.HAL2/BlockDevice/ATAPI.cs
- source/Cosmos.HAL2/BlockDevice/ATA_PIO.cs
- source/Cosmos.HAL2/BlockDevice/AtaPio.cs
- source/Cosmos.HAL2/BlockDevice/IDE.cs
Adds a basic ATAPI driver.
TODO
> Add ATAPI driver

- source/Cosmos.Build.Builder/App.xaml
- source/Cosmos.Build.Builder/App.xaml.cs
- source/Cosmos.Build.Builder/BuildTasks/ProcessBuildTaskBase.cs
- source/Cosmos.Build.Builder/Cosmos.Build.Builder.csproj
- source/Cosmos.Build.Builder/CosmosBuildDefinition.cs
- source/Cosmos.Build.Builder/Dependencies/InnoSetupDependency.cs
- source/Cosmos.Build.Builder/Dependencies/ProperRepoNameDependency.cs
- source/Cosmos.Build.Builder/Dependencies/ReposDependency.cs
- source/Cosmos.Build.Builder/Dependencies/VisualStudioDependency.cs
- source/Cosmos.Build.Builder/Dependencies/VisualStudioWorkloadsDependency.cs
- source/Cosmos.Build.Builder/ViewModels/DependencyInstallationDialogViewModel.cs
- source/Cosmos.Build.Builder/ViewModels/MainWindowViewModel.cs
- source/Cosmos.Build.Builder/Views/DependencyInstallationDialog.xaml
- source/Cosmos.Build.Builder/Views/MainWindow.xaml
- source/Cosmos.Build.Builder/Views/MessageBox.xaml
- source/Cosmos.Build.Builder/Views/MessageBox.xaml.cs
- source/Cosmos.Build.Builder/Views/VisualStudioInstanceDialog.xaml
Updates the Devkit installer UI.
Dark theme:
Light theme:
Dependency install dialog:
> [Installer] Update UI

- Docs/articles/Kernel/Network.md
- source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpClient.cs
- source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpCommandManager.cs
- source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpServer.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPClient.cs
- source/Cosmos.System2/Network/IPv4/TCP/TCPPacket.cs
- source/Cosmos.System2/Network/IPv4/TCP/Tcp.cs
- source/Cosmos.System2/Network/IPv4/TCP/TcpListener.cs
> FTP Server Implementation + TCB Implementation

- Docs/articles/Kernel/VFS.md
I've kind of rewrote the VFS article to be more clear, have the example code pieces more consistent, and also added a new section for formatting the drive. Some typos have also been fixed but there might also still be some.
> [Documentation] Improve VFS article

- Docs/articles/Kernel/CGS.md
There isn't a ton that I've changed, I've only fixed some typos, fixed the example code (by using Sys.Power.Shutdown() instead of Kernel.Stop(), for instance), refactored the implementation limitations section and a few other things in the introduction.
> [Documentation] Improve CGS article

- .github/ISSUE_TEMPLATE/build-error-and-visual-studio-problems.md
- .github/ISSUE_TEMPLATE/docs_or_website.md
Include information about the prerelease enabled in the nuget package manager
> Update issue templates

- Tests/Kernels/Cosmos.Kernel.Tests.DiskManager/System.FileSystem/DiskManagerTest.cs
- source/Cosmos.HAL2/BlockDevice/IDE.cs
- source/Cosmos.System2/FileSystem/CosmosVFS.cs
- source/Cosmos.System2/FileSystem/ISO9660/ISO9660DirectoryEntry.cs
- source/Cosmos.System2/FileSystem/ISO9660/ISO9660FileSystem.cs
- source/Cosmos.System2/FileSystem/ISO9660/ISO9660FileSystemFactory.cs
Implement ISO9660 file system, allowing users to read from a DVD drive
> [vfs] Implement ISO9660 file system

- source/Cosmos.System2/Network/IPv4/TCP/TCPClient.cs
- source/Cosmos.System2/Network/IPv4/TCP/Tcp.cs
- source/Cosmos.System2/Network/IPv4/TCP/TcpListener.cs
> Add ability to connect to the TcpListener again after client disconnected

- source/Cosmos.VS.DebugEngine/CosmosDebugEnginePackage.cs
> Revert "BindingRedirect versions updated."

- Directory.Build.props
- source/Cosmos.Build.Tasks/IL2CPU.cs
- source/Cosmos.Build.Tasks/build/Cosmos.Build.targets
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/OldCosmosPropertyPageControl.Designer.cs
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/OldCosmosPropertyPageControl.cs
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/OldCosmosPropertyPageControl.resx
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/ViewModels/CosmosPropertyPageViewModel.cs
Syslinux will enable graphic mode for you
todo:
> Add option in PropertyPages to compile with VBE enabled or not

- source/Cosmos.Build.Builder/Views/MainWindow.xaml
Make builder scroll bars work correctly
> Fix builder scroll bars

- source/Cosmos.Build.Tasks/build/Cosmos.Build.targets
Fix subdirectories for copying files into the ISO feature
> Fix subdirectories for ISO file copy

- Tests/Cosmos.TestRunner.Full/TestKernelSets.cs
- Tests/Kernels/ConsoleTest/Kernel.cs
- source/Cosmos.Core/IOGroup/TextScreen.cs
- source/Cosmos.HAL2/DebugTextScreen.cs
- source/Cosmos.HAL2/TextScreen.cs
- source/Cosmos.HAL2/TextScreenBase.cs
- source/Cosmos.System2/Console.cs
- source/Cosmos.System2_Plugs/System/ConsoleImpl.cs
The title explains explains everything.
Need a review so I know what to change, the code is a bit messy right now.
> Fix 90*60 Console functions not working

- Setup/Cosmos.iss
This PR should fix the cosmos.debug.kernel error
> Clear nuget cache in installer

- source/Cosmos.System2/Kernel.cs
> Implement Kernel.Restart();

- Tests/Cosmos.TestRunner.TestController/Assert.cs
- source/Cosmos.Core_Plugs/MathImpl.cs
- source/Cosmos.System2_Plugs/System/MathImpl.cs
Dependent on [XSharp PR](https://github.com/CosmosOS/XSharp/pull/58)
Fixed bug in assert also
> Added XS plug to make Math.Tan faster and safer

- Resources/Dependencies/DapperExtensions.StrongName/DapperExtensions.StrongName.csproj
- source/Cosmos.Build.Tasks/Cosmos.Build.Tasks.csproj
Depends on: https://github.com/CosmosOS/IL2CPU/pull/152
> Fix System.Runtime Error

- source/Cosmos.HAL2/PS2Controller.cs
> Don't lockup when unsupported PS2 Controller

- Docs/articles/Tests/TestRunner.md
Add information left behind in the wiki
> Update TestRunner article

- source/Cosmos.Build.Tasks/Cosmos.Build.Tasks.csproj
- source/Cosmos.Debug.Hosts/VMware.cs
Needs https://github.com/CosmosOS/IL2CPU/pull/156
> Debug fixes

- Docs/articles/Kernel/VFS.md
For now just remove old information
> Update information on disks

- source/Cosmos.Core_Plugs/Interop/GlobalizationImpl.cs
- source/Cosmos.Debug.Hosts/Qemu.cs
- source/Cosmos.VS.DebugEngine/AD7.Impl/AD7Process.cs
- source/Cosmos.VS.ProjectSystem/BuildSystem/Rules/CosmosPropertyPage.xaml
- source/Cosmos.VS.ProjectSystem/ProjectSystem/VS/PropertyPages/ProfilePresets.cs
Needs https://github.com/CosmosOS/Common/pull/8
- fix custom .exe location
- fix PropertyPage.xaml
> Qemu support fixes

- source/Cosmos.HAL2/PCIDevice.cs
This should make it easier to write your own drivers in the kernel
> Make PCI Read/Write register methods public

- README.md
List of changes done:
"exising" -> "existing"
"Github" -> "GitHub"
No issue reference because problem is too small to justify making one.
> Update README.md (Grammar, spelling)

- source/Cosmos.VS.ProjectSystem/ProjectTemplates/CSharp/Cosmos/Cosmos Kernel/CSharpProject.vstemplate
- source/Cosmos.VS.ProjectSystem/ProjectTemplates/FSharp/Cosmos/Cosmos Kernel/FSharpProject.vstemplate
- source/Cosmos.VS.ProjectSystem/ProjectTemplates/VisualBasic/Cosmos/Cosmos Kernel/VisualBasicProject.vstemplate
i just noticed there are no tags in VS templates. it looks bad. so i made this
> tags in VS templates

- Tests/Kernels/GraphicTest/Kernel.cs
- source/Cosmos.HAL2/PIT.cs
- source/Cosmos.System2/Graphics/Canvas.cs
[+] Added arc drawing (Resolves #1639)
> Add arc drawing to canvas

- source/Cosmos.Build.Builder/App.xaml
- source/Cosmos.Build.Builder/Cosmos.Build.Builder.csproj
- source/Cosmos.Build.Builder/Views/DependencyInstallationDialog.xaml
- source/Cosmos.Build.Builder/Views/DependencyInstallationDialog.xaml.cs
- source/Cosmos.Build.Builder/Views/MainWindow.xaml
- source/Cosmos.Build.Builder/Views/MainWindow.xaml.cs
- source/Cosmos.Build.Builder/Views/MessageBox.xaml
- source/Cosmos.Build.Builder/Views/MessageBox.xaml.cs
- source/Cosmos.Build.Builder/Views/VisualStudioInstanceDialog.xaml
- source/Cosmos.Build.Builder/Views/VisualStudioInstanceDialog.xaml.cs
Also fixed background color in a few dialogs
> Update WPF UI

- Docs/articles/GettingStarted.md
update `gettingstarted.md`. its clearly was updated, but not enough
> update docs a little bit

- .github/ISSUE_TEMPLATE/build-error-and-visual-studio-problems.md
- .github/ISSUE_TEMPLATE/installation-error.md
- .github/ISSUE_TEMPLATE/plug-request.md
there was some typos and incostinencies. i fixed them. ~probably made worse~
> fix issue templates

- source/Cosmos.Build.Builder/App.xaml.cs
- source/Cosmos.Build.Builder/Services/DialogService.cs
- source/Cosmos.Build.Builder/Services/IDialogService.cs
- source/Cosmos.Build.Builder/ViewModels/MainWindowLogger.cs
- source/Cosmos.Build.Builder/ViewModels/MainWindowViewModel.cs
- source/Cosmos.Build.Builder/Views/MainWindow.xaml
- source/Cosmos.Build.Builder/Views/MainWindow.xaml.cs
it looked bad so i refreshed it. i dont know how it looks on other windows versions so please leave a comment.
- i made ui some winui3-ish
- added individual section copying
- added rebuild action
- now "close when completed" is working (maybe)
> cosmos builder ui update

- source/Cosmos.Core/CPU.cs
> update cpu xmldocs

- Tests/Kernels/Cosmos.Compiler.Tests.TypeSystem/Kernel.cs
- source/Cosmos.Core/VTablesImpl.cs
- source/Cosmos.Core_Plugs/CosmosRuntimeType.cs
- source/Cosmos.Core_Plugs/System/TypeImpl.cs
Plug Type.GetType
Requires https://github.com/CosmosOS/IL2CPU/pull/179/
> Type Name support

- source/Cosmos.HAL2/SerialPort.cs
im so dumb. i wrote that code at evening and i forgot to add another com ports. sorry
> fix com ports 2-8

- source/Cosmos.System2_Plugs/System/Drawing/ColorImpl.cs
Updated the Microsoft link (it was for an old version of .NET & it was in deutsch) & updated the "Color name must be passed" string
> Strings update

- source/Cosmos.System2_Plugs/System/Threading/TimerImpl.cs
- source/Cosmos.System2_Plugs/System/Threading/TimerQueueImpl.cs
> Implement System.Threading.Timer

- source/Cosmos.Core_Plugs/MathFImpl.cs
This is a temporary implementation, it should be changed to use native code instead of casting types when possible.
> Implement MathF

- source/Cosmos.Debug.Kernel.Plugs.Asm/DebuggerAsm.cs
- source/Cosmos.Debug.Kernel/ConsoleDebugger.cs
- source/Cosmos.Debug.Kernel/Debugger.cs
I don't know how to test it so it might not work at all
> Implement string[] to the debugger

- Docs/articles/Installation/DevKit.md
> Fix minor typo

- source/Cosmos.Build.Tasks/ReadNasmMapToDebugInfo.cs
- source/Cosmos.VS.DebugEngine/AD7.Impl/AD7PendingBreakpoint.cs
- source/Cosmos.VS.DebugEngine/AD7.Impl/AD7Process.cs
- source/Cosmos.VS.DebugEngine/AD7.Impl/AD7StackFrame.cs
depends on https://github.com/CosmosOS/IL2CPU/pull/198
> Decrease number of operations

- appveyor.yml
update version to reflect last userkit
> update version to reflect last userkit

- source/Cosmos.Core/VTablesImpl.cs
Now shows the type the method was not found on
> Small error handling improvement in VTables

- Setup/Cosmos.iss
> Include VS installation code

- source/Cosmos.System2/Keyboard/ScanMaps/USDvorakLayout.cs
Added a copy of the dvorak keyboard layout I'm using in my Cosmos project.
> Adding US_Dvorak support

- source/Cosmos.Core_Plugs/System/ObjectImpl.cs
Adds a small Object.ToString implementation that shows
`<object of TYPENAME>`
so like
`<object of EventArgs>`
> Add Object.ToString

- source/Cosmos.Core_Plugs/System/StringImpl.cs
> Verify length when constructing a string

- README.md
I just wanna remove the issues box in readme because it wasnt really necessary and clogging up the mobile version of cosmos repo
> clogging issue box in readme

- source/Cosmos.System2_Plugs/System/ConsoleImpl.cs
> add setter for OutputEncoding and InputEncoding

- Examples/Basic Terminal Shell/Kernel.cs
Fixed a really dangerous, possible memory-leak causing typo.
hope this makes someones day :)
> Fixed Typo

- Docs/articles/Kernel/VFS.md
> 0: is now 0:\

- source/Cosmos.Core/GCImplementation.cs
- source/Cosmos.Core/Memory/RAT.cs
- source/Cosmos.Core/Multiboot/Multiboot2.cs
- source/Cosmos.Core/Multiboot/Tags/AcpiNew.cs
- source/Cosmos.Core/Multiboot/Tags/AcpiOld.cs
Fixes #2546. Also adds multiboot tags to detect ACPI
> Fix ACPI table overwrite

- source/Cosmos.System2_Plugs/System/IO/OSFileStreamStrategyImpl.cs
- source/Cosmos.System2_Plugs/System/Net/IPAddressImpl.cs
- source/Cosmos.System2_Plugs/System/Net/IPEndPointImpl.cs
- source/Cosmos.System2_Plugs/System/Net/Sockets/NetworkStreamImpl.cs
- source/Cosmos.System2_Plugs/System/Net/Sockets/SocketImpl.cs
- source/Cosmos.System2_Plugs/System/Net/Sockets/TcpClientImpl.cs
- source/Cosmos.System2_Plugs/System/Net/Sockets/TcpListenerImpl.cs
Nothing static in System.Net plugs (except IpAddress due to stack corruption)
> 🐛 Fix multiple stream conflict

- source/Cosmos.System2/IO/StdInReader.cs
- source/Cosmos.System2/Keyboard/ScanMaps/DEStandardLayout.cs
- source/Cosmos.System2/Keyboard/ScanMaps/ESStandardLayout.cs
- source/Cosmos.System2/Keyboard/ScanMaps/FRStandardLayout.cs
- source/Cosmos.System2/Keyboard/ScanMaps/GBStandardLayout.cs
- source/Cosmos.System2/Keyboard/ScanMaps/TRStandardLayout.cs
- source/Cosmos.System2/Keyboard/ScanMaps/USDvorakLayout.cs
- source/Cosmos.System2/Keyboard/ScanMaps/USStandardLayout.cs
> Solve #2894

- source/Cosmos.System2/Graphics/VGACanvas.cs
Now you can see an available VGA video modes in Visual Studio.
> Available VGA modes list in VS.

- Makefile
Fix the `cp: cannot stat '/home/runner/cosmos/Cosmos/../IL2CPU/artifacts/Debug/nupkg/*.nupkg': No such file or directory` problem
But we still have https://github.com/CosmosOS/CosmosFtp/issues/5
> 🐛 Fix linux build
